SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[viva_insights_person]
( 
	[PersonId] [nvarchar](4000)  NOT NULL PRIMARY KEY NONCLUSTERED NOT ENFORCED,
	[Date] [date]  NOT NULL,
	[Organization] [nvarchar](4000)  NULL,
	[LevelDesignation] [nvarchar](4000)  NULL,
	[Workweek_span] [float]  NULL,
	[Meetings_with_skip_level] [int]  NULL,
	[Meeting_hours_with_skip_level] [float]  NULL,
	[Generated_workload_email_hours] [float]  NULL,
	[Generated_workload_email_recipients] [int]  NULL,
	[Generated_workload_instant_messages_hours] [int]  NULL,
	[Generated_workload_instant_messages_recipients] [int]  NULL,
	[Generated_reactions_to_posts] [int]  NULL,
	[Generated_replies_to_posts] [int]  NULL,
	[Generated_workload_call_hours] [int]  NULL,
	[Generated_workload_call_participants] [int]  NULL,
	[Generated_workload_calls_organized] [int]  NULL,
	[External_network_size] [int]  NULL,
	[Internal_network_size] [int]  NULL,
	[Networking_outside_company] [int]  NULL,
	[Networking_outside_organization] [int]  NULL,
	[Multitasking_hours] [float]  NULL,
	[After_hours_meeting_hours] [float]  NULL,
	[Open_1_hour_block] [int]  NULL,
	[Open_2_hour_blocks] [int]  NULL,
	[Total_focus_hours] [float]  NULL,
	[Low_quality_meeting_hours] [float]  NULL,
	[Meetings] [int]  NULL,
	[Meeting_hours] [float]  NULL,
	[Conflicting_meeting_hours] [float]  NULL,
	[Multitasking_meeting_hours] [float]  NULL,
	[Redundant_meeting_hours__lower_level_] [float]  NULL,
	[Redundant_meeting_hours__organizational_] [int]  NULL,
	[Time_in_self_organized_meetings] [float]  NULL,
	[Meeting_hours_during_working_hours] [float]  NULL,
	[Generated_workload_meeting_attendees] [int]  NULL,
	[Generated_workload_meeting_hours] [float]  NULL,
	[Generated_workload_meetings_organized] [int]  NULL,
	[Manager_coaching_hours_1_on_1] [float]  NULL,
	[Meetings_with_manager] [int]  NULL,
	[Meeting_hours_with_manager] [float]  NULL,
	[Meetings_with_manager_1_on_1] [int]  NULL,
	[Meeting_hours_with_manager_1_on_1] [float]  NULL,
	[After_hours_instant_messages] [int]  NULL,
	[Instant_messages_sent] [int]  NULL,
	[Instant_Message_hours] [int]  NULL,
	[Working_hours_instant_messages] [int]  NULL,
	[Emails_sent] [int]  NULL,
	[Email_hours] [float]  NULL,
	[Uninterrupted_focus_hours] [float]  NULL,
	[After_hours_collaboration_hours] [float]  NULL,
	[Collaboration_hours_external] [float]  NULL,
	[Collaboration_hours] [float]  NULL,
	[Working_hours_collaboration_hours] [float]  NULL,
	[After_hours_email_hours] [float]  NULL,
	[Working_hours_email_hours] [float]  NULL,
	[Channels_with_active_engagement] [int]  NULL,
	[Teams_with_active_engagement] [int]  NULL,
	[After_hours_channel_message_hours] [int]  NULL,
	[Channel_message_hours] [int]  NULL,
	[Channel_messages_sent] [int]  NULL,
	[Channel_reactions] [int]  NULL,
	[Channel_visits] [int]  NULL,
	[Working_hours_channel_message_hours] [int]  NULL,
	[After_hours_in_calls] [int]  NULL,
	[Total_calls] [int]  NULL,
	[Call_hours] [int]  NULL,
	[Working_hours_in_calls] [int]  NULL,
	[IsInternal] [bit]  NULL,
	[IsActive] [bit]  NULL,
	[WorkingStartTimeSetInOutlook] [nvarchar](4000)  NULL,
	[WorkingEndTimeSetInOutlook] [nvarchar](4000)  NULL,
	[WorkingDaysSetInOutlook] [nvarchar](4000)  NULL
)

GO